name: JAVA CI PIPELINE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3
      - name: Set up working directory
        working-directory: app_code  

      - name: List files in the repository
        run: ls -la  # This will show the contents of the directory

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: chmod +x app_code/gradlew # Ensure gradlew has executable permissions

      - name: Build with Gradle
        run: ./gradlew build
