name: JAVA CI PIPELINE

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check the source code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3  # Set up JDK 11 for the build
        with:
          java-version: '11'  # Use Java 11 
          distribution: 'adoptium'

      - name: Build with gradle 
        uses: ./gradlew build  
