name: JAVA CI PIPELINE

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check the code 
        uses: action/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2  # Set up JDK 11 for the build
        with:
          java-version: '11'  # Use Java 11 
           
      - name: Build with gradle 
        uses: ./gradlew build  